### ISSUE TITLE
Enhance user list view

### ISSUE THREAD

**Issue by KevinTss** [KevinTss/brussels-salsa-project#10]
List of users should show more informations
- Full name
- Classes levels

-> Create a `user card` element to re-use everywhere

<img width="1077" alt="Screenshot 2022-03-27 at 13 33 44" src="https://user-images.githubusercontent.com/39580007/160279661-5163389d-1512-49bd-96dc-9d73383365db.png">

<img width="1420" alt="Screenshot 2022-03-27 at 13 31 46" src="https://user-images.githubusercontent.com/39580007/160279660-824acd25-9c93-4a92-9c21-628ccc016ce5.png">

**Comment by salsaproject** [comment]
List is much better and easier to follow.

Small detail on the display in smaller screens, but for the moment I leave up to you to see how you want to backlog it - just shrink the window (can't attach a screenshot here).

Managing the levels also works well, on the screen itself and with the interaction on entering a class.
Note: the user has to refresh the screen after the change of level to be in effect. @KevinTss is the application running from the browser or the user information stored and used locally when we want to enter a class? Just to understand what the app is doing

**Comment by KevinTss** [comment]
Yes indeed the user related informations are fetch add the login moment.
Not sure to understand the question but for the app is indeed run in the browser. When you create a classe the user should see it if he is connected during the day where the classe has been set.

**Comment by salsaproject** [comment]
And for that connection he/she needs to refresh the browser, correct?

**Comment by KevinTss** [comment]
Yes exactly
