### ISSUE TITLE
Better way to arrange recurring classes list

### ISSUE THREAD

**Issue by KevinTss** [KevinTss/brussels-salsa-project#14]
is there a better way to arrange the list of recurring classes? https://app.asana.com/0/1201930492679079/1202018808715461

**Comment by KevinTss** [comment]
@salsaproject Can you define what do you want exactly?
- Be able to sort yourself (like drag and drop) the list
- Or have the list sorted by day and time for example

**Comment by salsaproject** [comment]
Sure. Simple thing sorted by week day, then by hour. No need to allow customizations at this time

**Comment by salsaproject** [comment]
It looks ok.
I found one trick though. I changed the hour of one class and it didn't sorted again (check classes on wednesday). But if changing the week day, it works instantly.

**Comment by KevinTss** [comment]
Good point indeed, there are no filter on that, I will change that as a low prio change
