### ISSUE TITLE
As an admin, I should see the list of users in my admin panel

### ISSUE THREAD

**Issue by KevinTss** [KevinTss/brussels-salsa-project#2]

**Comment by salsaproject** [comment]
List exists.
Possible to show the level/class already on the list in front of the mail?
Possible to put the link details in front of the email and not at the bottom? (of course in mobiles with the responsive design it can go where it fits)

**Comment by KevinTss** [comment]
> List exists. Possible to show the level/class already on the list in front of the mail? Possible to put the link details in front of the email and not at the bottom? (of course in mobiles with the responsive design it can go where it fits)

Track of this improvement [here](https://github.com/KevinTss/brussels-salsa-project/issues/10)
