### ISSUE TITLE
As an admin, I can add a user to a class

### ISSUE THREAD

**Issue by KevinTss** [KevinTss/brussels-salsa-project#3]

**Comment by KevinTss** [comment]
> It works. Nice integration with the student list. Is it possible to insert a name of a person not in the list? Can I remove dancers too? Sometimes people don't show up.

I create a new issue for the name [here](https://github.com/KevinTss/brussels-salsa-project/issues/8)
For the removing yes it's possible but here you're talking about the `no-showing up` things which is more a `presence system` feature no? I also add that [here](https://github.com/KevinTss/brussels-salsa-project/issues/9)

**Comment by salsaproject** [comment]
For removing it's both.


ᐧ
