### ISSUE TITLE
Add logs for fetching data actions

### ISSUE THREAD

**Issue by KevinTss** [KevinTss/brussels-salsa-project#7]
On some browsers, for unknown reasons, the available classes are not shown.
Adding logs into the console could help to understand what happen on production.

**Comment by salsaproject** [comment]
Is it something I could test here or shall we move this to production?

**Comment by KevinTss** [comment]
> Is it something I could test here or shall we move this to production?

It's just some logs added in the console for helping to debug when we have problem like we had together with sharing screen last time. Nothing to really test here actually

And for now, production is way behind the staging one, s I will make a push to production when we have a more finished version in staging

**Comment by salsaproject** [comment]
OK
